dsp_line_from_dsp – fenvelopes
dsp_line_from_dsp Function
MIT
30 statements
Source File
public function dsp_line_from_dsp(dsp, pt_1, pt_2, del_S0, alpha0) result(envels)
Uses
linalg
stdlib_optval
legacy_ar_models
Calculate a DSP line from an already found double saturation point (dsp) between two PT lines (pt_1and pt_2).
Arguments
Type Intent Optional Attributes Name
type(point), intent(in) :: dsp
DSP point
type(envelope), intent(in) :: pt_1
PT envelope
type(envelope), intent(in) :: pt_2
PT envelope
real(kind=pr), optional :: del_S0
Initial step size, defaults to 0.01
real(kind=pr), optional :: alpha0
Initial (\alpha)\, defaults to 0
Return Value type(injelope)(2)
Output envelopes
Calls
Contents
Variables
X alpha del_S dzda i j lnKx lnKy ns p t z
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: X(2*nc+3)
real(kind=pr), public :: alpha
real(kind=pr), public :: del_S
real(kind=pr), public :: dzda(nc)
integer, public :: i
integer, public :: j
real(kind=pr), public :: lnKx(nc)
real(kind=pr), public :: lnKy(nc)
integer, public :: ns
real(kind=pr), public :: p
real(kind=pr), public :: t
real(kind=pr), public :: z(nc)
Call graph
dsp_line_from_dsp calls optval, interpol, get_z, dsp_line
dsp_line calls update_spec, fix_step, full_newton, progress_bar, str, break_conditions_dsp_line
update_spec calls solve_system
full_newton calls optval, solve_system
solve_system calls dgesv