dsp_line_from_dsp_px – fenvelopes
dsp_line_from_dsp_px Function
MIT
33 statements
Source File
public function dsp_line_from_dsp_px(dsp, px_1, px_2, del_S0, alpha0) result(envels)
Uses
linalg
stdlib_optval
inj_envelopes
legacy_ar_models
Calculate a DSP line from an already found double saturation point (dsp) between two P lines (px_1and px_2).
Arguments
Type Intent Optional Attributes Name
type(point), intent(in) :: dsp
Double Saturation Point
type(injelope), intent(in) :: px_1
P line
type(injelope), intent(in) :: px_2
P line
real(kind=pr), optional :: del_S0
Initial step size, defaults to 0.01
real(kind=pr), optional :: alpha0
Initial , defaults to 0
Return Value type(injelope)(2)
DSP lines
Calls
Called by
Contents
Variables
X alpha del_S dzda i j lnKx lnKy ns p t z
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: X(2*nc+3)
real(kind=pr), public :: alpha
real(kind=pr), public :: del_S
real(kind=pr), public :: dzda(nc)
integer, public :: i
integer, public :: j
real(kind=pr), public :: lnKx(nc)
real(kind=pr), public :: lnKy(nc)
integer, public :: ns
real(kind=pr), public :: p
real(kind=pr), public :: t
real(kind=pr), public :: z(nc)
Call graph
dsp_line_from_dsp_px calls optval, interpol, get_z, dsp_line
dsp_line calls update_spec, fix_step, full_newton, progress_bar, str, break_conditions_dsp_line
update_spec calls solve_system
full_newton calls optval, solve_system
solve_system calls dgesv
px_envelopes calls dsp_line_from_dsp_px
main calls px_envelopes