dsp_line – fenvelopes
dsp_line Subroutine
MIT
70 statements
Source File
public subroutine dsp_line(X0, spec_number, del_S0, envels)
Uses
constants
io
Subroutine to calculate Px phase envelopes via continuation method. Three phases version.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X0(:)
Vector of variables
integer, intent(in) :: spec_number
Number of specification
real(kind=pr), intent(in) :: del_S0
type(injelope), intent(out) :: envels
Calculated envelopes
Calls
Called by
Contents
Variables
F S X XS cps dF dXdS del_S fname_env funit_output i iters n ns point
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F(size(X0))
real(kind=pr), public :: S
real(kind=pr), public :: X(size(X0))
real(kind=pr), public :: XS(max_points,size(X0))
type(critical_point), public, allocatable :: cps(:)
real(kind=pr), public :: dF(size(X0),size(X0))
real(kind=pr), public :: dXdS(size(X0))
real(kind=pr), public :: del_S
character(len=254), public :: fname_env
integer, public :: funit_output
integer, public :: i
integer, public :: iters
integer, public :: n
integer, public :: ns
integer, public :: point
Call graph
dsp_line calls update_spec, fix_step, full_newton, progress_bar, str, break_conditions_dsp_line
update_spec calls solve_system
full_newton calls solve_system, optval
solve_system calls dgesv
dsp_line_from_dsp calls dsp_line
dsp_line_from_dsp_px calls dsp_line
px_envelopes calls dsp_line_from_dsp_px
main calls px_envelopes