envelope2 – fenvelopes
envelope2 Subroutine
MIT
235 statements
Source File
public subroutine envelope2(ichoice, n, z, T, P, KFACT, n_points, Tv, Pv, Dv, ncri, icri, Tcri, Pcri, Dcri, this_envelope)
Uses
dtypes
linalg
io
constants
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ichoice
integer, intent(in) :: n
real(kind=pr), intent(in) :: z(n)
real(kind=pr) :: T
real(kind=pr) :: P
real(kind=pr), intent(inout) :: KFACT(n)
integer, intent(out) :: n_points
real(kind=pr), intent(out) :: Tv(max_points)
real(kind=pr), intent(out) :: Pv(max_points)
real(kind=pr), intent(out) :: Dv(max_points)
integer, intent(out) :: ncri
integer, intent(out), dimension(4) :: icri
real(kind=pr), intent(out), dimension(4) :: Tcri(4)
real(kind=pr), intent(out), dimension(4) :: Pcri(4)
real(kind=pr), intent(out), dimension(4) :: Dcri(4)
type(envelope), intent(out) :: this_envelope
Calls
Called by
Contents
Variables
AJ F JAC S Told Told2 Vx X Xold Xold2 bd black_i critical_points dFdS dXdS delS delX delta_t extra_slope fname_env frac funit_output i incipient_phase iter ix iy lnK_extrapolated maxP max_iter minT minmaxT ns passingcri run stepx tmp_logk tmp_logphi y
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, dimension(n + 2, n + 2) :: AJ
real(kind=pr), public, dimension(n + 2) :: F
real(kind=pr), public, dimension(n + 2, n + 2) :: JAC
real(kind=pr), public :: S
real(kind=pr), public :: Told
real(kind=pr), public :: Told2
real(kind=pr), public :: Vx
real(kind=pr), public, dimension(n + 2) :: X
real(kind=pr), public, dimension(n + 2) :: Xold
real(kind=pr), public, dimension(n + 2) :: Xold2
real(kind=pr), public, dimension(n + 2) :: bd
integer, public :: black_i
type(critical_point), public, allocatable :: critical_points(:)
real(kind=pr), public, dimension(n + 2) :: dFdS
real(kind=pr), public, dimension(n + 2) :: dXdS
real(kind=pr), public :: delS
real(kind=pr), public, dimension(n + 2) :: delX
real(kind=pr), public :: delta_t
real(kind=pr), public :: extra_slope(n+2)
character(len=254), public :: fname_env
real(kind=pr), public :: frac
integer, public :: funit_output
integer, public :: i
character(len=:), public, allocatable :: incipient_phase
integer, public :: iter
integer, public :: ix
integer, public :: iy
real(kind=pr), public :: lnK_extrapolated(n)
real(kind=pr), public :: maxP
integer, public :: max_iter
logical, public :: minT
logical, public :: minmaxT
integer, public :: ns
logical, public :: passingcri
logical, public :: run
real(kind=pr), public :: stepx
real(kind=pr), public :: tmp_logk(max_points,n)
real(kind=pr), public :: tmp_logphi(max_points,n)
real(kind=pr), public, dimension(n) :: y
Call graph
envelope2 calls str, f2, xin, m, solve_system, fix_delx, update_specification, delta_x
f2 calls termo
solve_system calls dgesv
update_specification calls solve_system, dfds
pt_envelopes calls envelope2
main calls pt_envelopes