flash – fenvelopes
flash Subroutine
MIT
151 statements
Source File
public subroutine flash(spec, FIRST, z, t, p, v, x, y, rho_x, rho_y, beta, iter)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: spec
Flash specification [PT | VT]
logical, intent(inout) :: FIRST
real(kind=8), intent(in) :: z(:)
real(kind=8), intent(in) :: t
real(kind=8) :: p
real(kind=8) :: v
real(kind=8), intent(out), dimension(size(z)) :: x
real(kind=8), intent(out), dimension(size(z)) :: y
real(kind=8), intent(out) :: rho_x
real(kind=8), intent(out) :: rho_y
real(kind=8), intent(out) :: beta
integer, intent(out) :: iter
Calls
Contents
Variables
AUXK DLPHIP DLPHIT DPVl FUGN KFACT LOG_K MTYP PHILOGx PHILOGy Vx Vy aux bij bmax bmin bx dVydVl denom dg dh dpv dpvv g g0 g1 h i iterv j logKold log_k2 nco pl pold pold2 pv savek step stepv stopflash told told2 varKold var_K
Variables
Type Visibility Attributes Name Initial
real(kind=8), public, dimension(n) :: AUXK
real(kind=8), public, dimension(n) :: DLPHIP
real(kind=8), public, dimension(n) :: DLPHIT
real(kind=8), public :: DPVl
real(kind=8), public, dimension(n, n) :: FUGN
real(kind=8), public, dimension(n) :: KFACT
real(kind=8), public, dimension(n) :: LOG_K
integer, public :: MTYP
real(kind=8), public, dimension(n) :: PHILOGx
real(kind=8), public, dimension(n) :: PHILOGy
real(kind=8), public :: Vx
real(kind=8), public :: Vy
real(kind=8), public :: aux
real(kind=8), public :: bij(n,n)
real(kind=8), public :: bmax
real(kind=8), public :: bmin
real(kind=8), public :: bx
real(kind=8), public :: dVydVl
real(kind=8), public, dimension(n) :: denom
real(kind=8), public :: dg
real(kind=8), public :: dh
real(kind=8), public :: dpv
real(kind=8), public :: dpvv
real(kind=8), public :: g
real(kind=8), public :: g0
real(kind=8), public :: g1
real(kind=8), public :: h
integer, public :: i
integer, public :: iterv
integer, public :: j
real(kind=8), public, dimension(n) :: logKold
real(kind=8), public :: log_k2(n)
integer, public :: nco
real(kind=8), public :: pl
real(kind=8), public :: pold
real(kind=8), public :: pold2
real(kind=8), public :: pv
real(kind=8), public :: savek(n)
real(kind=8), public :: step
real(kind=8), public :: stepv
logical, public :: stopflash
real(kind=8), public :: told
real(kind=8), public :: told2
real(kind=8), public, dimension(n) :: varKold
real(kind=8), public, dimension(n) :: var_K
Call graph
flash calls ztvtermo, betalimits, betato01, termo