full_newton – fenvelopes
full_newton Subroutine
MIT
54 statements
Source File
public subroutine full_newton(fun, iters, X, ns, S, max_iters, F, df, solvetol)
Uses
stdlib_optval
constants
Subroutine to solve a point in the envelope.
Procedure that solves a point with the Newton-Raphson method.
Arguments
Type Intent Optional Attributes Name
public subroutine fun(X, ns, S, F, dF)
Function to solve
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
integer, intent(in) :: ns
real(kind=pr), intent(in) :: S
real(kind=pr), intent(out) :: F(size(X))
real(kind=pr), intent(out) :: dF(size(X),size(X))
integer, intent(out) :: iters
Number of iterations needed
real(kind=pr), intent(inout) :: X(:)
Variables vector
integer, intent(in) :: ns
Number of specification
real(kind=pr), intent(in) :: S
Specification value
integer, intent(in) :: max_iters
Maximum iterations
real(kind=pr), intent(out) :: F(size(X))
Function values at solved point
real(kind=pr), intent(out) :: df(size(X),size(X))
Jacobian values
real(kind=pr), intent(in), optional :: solvetol
Calls
Called by
Contents
Variables
A b dX fjac funit fvec info ldfjac lwa n tol wa
Subroutines
fcn
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: A(size(X),size(X))
real(kind=pr), public :: b(size(X))
real(kind=pr), public :: dX(size(X))
real(kind=pr), public :: fjac(size(x),size(x))
integer, public :: funit
real(kind=pr), public :: fvec(size(x))
integer, public :: info
integer, public :: ldfjac
integer, public :: lwa
integer, public :: n
real(kind=pr), public :: tol
real(kind=pr), public, allocatable :: wa(:)
Subroutines
subroutine fcn(N, x, fvec, fjac, ldfjac, iflag)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
real(kind=pr), intent(in) :: x(n)
real(kind=pr), intent(inout) :: fvec(n)
real(kind=pr), intent(inout) :: fjac(ldfjac,n)
integer, intent(in) :: ldfjac
integer, intent(inout) :: iflag
Call graph
full_newton calls optval, solve_system
solve_system calls dgesv
pt_envelope_three_phase calls full_newton
injection_envelope_three_phase calls full_newton
injection_envelope calls full_newton
dsp_line calls full_newton
pt_three_phase_from_intersection calls pt_envelope_three_phase
px_three_phase_from_inter calls injection_envelope_three_phase
pt_envelopes calls pt_envelope_three_phase, pt_three_phase_from_intersection
px_three_phase_from_pt calls injection_envelope_three_phase
px_hpl_line calls injection_envelope
px_two_phase_from_pt calls injection_envelope
dsp_line_from_dsp calls dsp_line
dsp_line_from_dsp_px calls dsp_line
px_envelopes calls px_three_phase_from_inter, px_three_phase_from_pt, px_hpl_line, px_two_phase_from_pt, dsp_line_from_dsp_px
main calls pt_envelopes, px_envelopes