get_z – fenvelopes
get_z Subroutine
MIT
16 statements
Source File
public subroutine get_z(alpha, z, dzda)
Calculate the fluid composition based on an amount of addition of second fluid.
The injection can be considered as two kinds of injection: - Displacement: - Addition:
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: alpha
Addition percentaje
real(kind=pr), intent(out) :: z(size(z_0))
New composition
real(kind=pr), intent(out), optional :: dzda(size(z_0))
Derivative wrt
Called by
Contents
None
Call graph
dsp_line_from_dsp_px calls get_z
dsp_line_from_dsp calls get_z
dsp_line_f calls get_z
px_three_phase_from_inter calls get_z, injection_envelope_three_phase
f_injection calls get_z
injection_envelope calls get_z
injection_envelope_three_phase calls get_z
f_injection_three_phases calls get_z
main calls get_z, px_envelopes
px_hpl_line calls foo, injection_envelope
px_three_phase_from_pt calls injection_envelope_three_phase
px_envelopes calls dsp_line_from_dsp_px, px_three_phase_from_inter, px_hpl_line, px_three_phase_from_pt, px_two_phase_from_pt
px_two_phase_from_pt calls injection_envelope