get_case – fenvelopes
get_case Subroutine
MIT
48 statements
Source File
public subroutine get_case(dew, bub, hpl, intersections, self_intersections, this_case)
Uses
linalg
Arguments
Type Intent Optional Attributes Name
type(envelope), intent(in) :: dew
type(envelope), intent(in) :: bub
type(envelope), intent(in) :: hpl
type(point), intent(out), allocatable :: intersections(:)
type(point), intent(out), allocatable :: self_intersections(:)
character(len=:), intent(out), allocatable :: this_case
Calls
Called by
Contents
Variables
inter_dew_bub inter_hpl_bub inter_hpl_dew self_inter_dew
Variables
Type Visibility Attributes Name Initial
type(point), public, allocatable :: inter_dew_bub(:)
type(point), public, allocatable :: inter_hpl_bub(:)
type(point), public, allocatable :: inter_hpl_dew(:)
type(point), public, allocatable :: self_inter_dew(:)
Call graph
get_case calls intersection
intersection calls intersect_two_lines, intersect_one_line
intersect_two_lines calls intersects
intersect_one_line calls intersects
intersects calls solve_system
solve_system calls dgesv
pt_envelopes calls get_case
main calls pt_envelopes