injection_envelope_three_phase – fenvelopes
injection_envelope_three_phase Subroutine
MIT
125 statements
Source File
public subroutine injection_envelope_three_phase(X0, spec_number, del_S0, envels)
Uses
io
constants
Subroutine to calculate Px phase envelopes via continuation method. Three phases version.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X0(:)
Vector of variables
integer, intent(in) :: spec_number
Number of specification
real(kind=pr), intent(in) :: del_S0
type(injelope), intent(out) :: envels
Calculated envelopes
Calls
Called by
Contents
Variables
F S X XS alpha beta cps dF dXdS del_S fname_env funit_output i iters lnKx lnKy lnP n ns point z
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F(size(X0))
real(kind=pr), public :: S
real(kind=pr), public, target :: X(size(X0))
real(kind=pr), public :: XS(max_points,size(X0))
real(kind=pr), public, pointer :: alpha
real(kind=pr), public, pointer :: beta
type(critical_point), public, allocatable :: cps(:)
real(kind=pr), public :: dF(size(X0),size(X0))
real(kind=pr), public :: dXdS(size(X0))
real(kind=pr), public :: del_S
character(len=254), public :: fname_env
integer, public :: funit_output
integer, public :: i
integer, public :: iters
real(kind=pr), public, pointer :: lnKx(:)
real(kind=pr), public, pointer :: lnKy(:)
real(kind=pr), public, pointer :: lnP
integer, public :: n
integer, public :: ns
integer, public :: point
real(kind=pr), public :: z(size(z_0))
Call graph
injection_envelope_three_phase calls update_spec, break_conditions_three_phases, knew, get_z, full_newton, progress_bar, str, dxds_in
update_spec calls solve_system
full_newton calls solve_system
solve_system calls dgesv
px_three_phase_from_inter calls injection_envelope_three_phase
px_three_phase_from_pt calls injection_envelope_three_phase
px_envelopes calls px_three_phase_from_inter, px_three_phase_from_pt
main calls px_envelopes