injection_envelope – fenvelopes
injection_envelope Subroutine
MIT
93 statements
Source File
public subroutine injection_envelope(X0, spec_number, del_S0, envels)
Uses
constants
io
Subroutine to calculate Px phase envelopes via continuation method
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X0(:)
Vector of variables
integer, intent(in) :: spec_number
Number of specification
real(kind=pr), intent(in) :: del_S0
type(injelope), intent(out) :: envels
Calculated envelopes
Calls
Called by
Contents
Variables
F S X XS cps dF dXdS del_S fname_env funit_output i iters n ns point z
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F(size(X0))
real(kind=pr), public :: S
real(kind=pr), public :: X(size(X0))
real(kind=pr), public :: XS(max_points,size(X0))
type(critical_point), public, allocatable :: cps(:)
real(kind=pr), public :: dF(size(X0),size(X0))
real(kind=pr), public :: dXdS(size(X0))
real(kind=pr), public :: del_S
character(len=254), public :: fname_env
integer, public :: funit_output
integer, public :: i
integer, public :: iters
integer, public :: n
integer, public :: ns
integer, public :: point
real(kind=pr), public :: z(size(X0)-2)
Call graph
injection_envelope calls get_z, update_spec, xnew, fix_step_two_phases, full_newton, progress_bar, str, knew, break_conditions
update_spec calls solve_system
full_newton calls solve_system, optval
solve_system calls dgesv
px_hpl_line calls injection_envelope
px_two_phase_from_pt calls injection_envelope
px_envelopes calls px_hpl_line, px_two_phase_from_pt
main calls px_envelopes