intersect_one_line – fenvelopes
intersect_one_line Function
MIT
24 statements
Source File
public function intersect_one_line(lx, ly) result(intersections)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: lx(:)
real(kind=pr), intent(in) :: ly(:)
Return Value type(point),allocatable,(:)
Calls
Called by
Contents
Variables
i j s t x xold y yold
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
real(kind=pr), public :: s
real(kind=pr), public :: t
real(kind=pr), public :: x
real(kind=pr), public :: xold = 9999
real(kind=pr), public :: y
real(kind=pr), public :: yold = 9999
Call graph
intersect_one_line calls intersects
intersects calls solve_system
solve_system calls dgesv
intersection calls intersect_one_line
get_case calls intersection
px_envelopes calls intersection
pt_envelopes calls get_case
main calls px_envelopes, pt_envelopes