intersects – fenvelopes
intersects Subroutine
MIT
11 statements
Source File
public subroutine intersects(x1, x2, x3, x4, y1, y2, y3, y4, s, t)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: x1
real(kind=pr), intent(in) :: x2
real(kind=pr), intent(in) :: x3
real(kind=pr), intent(in) :: x4
real(kind=pr), intent(in) :: y1
real(kind=pr), intent(in) :: y2
real(kind=pr), intent(in) :: y3
real(kind=pr), intent(in) :: y4
real(kind=pr), intent(out) :: s
real(kind=pr), intent(out) :: t
Calls
Called by
Contents
Variables
A b tmp
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: A(2,2)
real(kind=pr), public :: b(2)
real(kind=pr), public :: tmp
Call graph
intersects calls solve_system
solve_system calls dgesv
intersect_one_line calls intersects
intersect_two_lines calls intersects
intersection calls intersect_one_line, intersect_two_lines
get_case calls intersection
px_envelopes calls intersection
pt_envelopes calls get_case
main calls px_envelopes, pt_envelopes