k_wilson – fenvelopes
k_wilson Function
MIT
6 statements
Source File
public function k_wilson(t, p) result(k)
Uses
legacy_ar_models
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: t
real(kind=pr), intent(in) :: p
Return Value real(kind=pr)(size(pc))
Called by
Contents
None
Call graph
k_wilson_bubble calls k_wilson
pt_envelopes calls k_wilson, k_wilson_bubble
main calls pt_envelopes