pt_envelope_three_phase – fenvelopes
pt_envelope_three_phase Subroutine
MIT
113 statements
Source File
public subroutine pt_envelope_three_phase(X0, spec_number, del_S0, envel)
Uses
constants
io
Subroutine to calculate Px phase envelopes via continuation method. Three phases version.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X0(:)
Vector of variables
integer, intent(in) :: spec_number
Number of specification
real(kind=pr), intent(in) :: del_S0
type(PTEnvel3), intent(out) :: envel
Calculated envelopes
Calls
Called by
Contents
Variables
F S X XS cps dF dXdS del_S fname_env funit_output i iters n ns point
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F(size(X0))
real(kind=pr), public :: S
real(kind=pr), public :: X(size(X0))
real(kind=pr), public :: XS(max_points,size(X0))
type(critical_point), public, allocatable :: cps(:)
real(kind=pr), public :: dF(size(X0),size(X0))
real(kind=pr), public :: dXdS(size(X0))
real(kind=pr), public :: del_S
character(len=254), public :: fname_env
integer, public :: funit_output
integer, public :: i
integer, public :: iters
integer, public :: n
integer, public :: ns
integer, public :: point
Call graph
pt_envelope_three_phase calls xnew, k, break_conditions_three_phases, dxds_in, str, full_newton, solve_system, progress_bar, knew
full_newton calls solve_system, optval
solve_system calls dgesv
pt_three_phase_from_intersection calls pt_envelope_three_phase
pt_envelopes calls pt_envelope_three_phase, pt_three_phase_from_intersection
main calls pt_envelopes