pt_envelopes – fenvelopes
pt_envelopes Subroutine
MIT
89 statements
Source File
subroutine pt_envelopes()
Uses
linalg
envelopes
legacy_ar_models
dsp_lines
Calculation of PT envelopes of the main system.
Arguments
None
Calls
Called by
Contents
Variables
dcri dv i icri intersections k n n_points ncri p pcri pt_case pv self_intersections t tcri tv
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: dcri(4)
real(kind=pr), public, allocatable :: dv(:)
integer, public :: i
integer, public :: icri(4)
type(point), public, allocatable :: intersections(:)
real(kind=pr), public, allocatable :: k(:)
integer, public :: n
integer, public :: n_points
integer, public :: ncri
real(kind=pr), public :: p
real(kind=pr), public :: pcri(4)
character(len=:), public, allocatable :: pt_case
real(kind=pr), public, allocatable :: pv(:)
type(point), public, allocatable :: self_intersections(:)
real(kind=pr), public :: t
real(kind=pr), public :: tcri(4)
real(kind=pr), public, allocatable :: tv(:)
Call graph
pt_envelopes calls k_wilson_bubble, dsp_line_from_dsp, find_hpl, k_wilson, get_case, pt_three_phase_from_intersection, p_wilson, envelope2, dsps
k_wilson_bubble calls k_wilson
dsp_line_from_dsp calls optval, interpol, get_z, dsp_line
find_hpl calls z, termo
get_case calls intersection
pt_three_phase_from_intersection calls pt_envelope_three_phase, interpol
envelope2 calls solve_system, xin, str, fix_delx, f2, update_specification, m, delta_x
intersection calls intersect_two_lines, intersect_one_line
pt_envelope_three_phase calls solve_system, str, knew, full_newton, progress_bar, xnew, k, dxds_in, break_conditions_three_phases
solve_system calls dgesv
dsp_line calls str, update_spec, full_newton, progress_bar, fix_step, break_conditions_dsp_line
f2 calls termo
update_specification calls solve_system, dfds
intersect_two_lines calls intersects
intersect_one_line calls intersects
update_spec calls solve_system
full_newton calls solve_system
intersects calls solve_system
main calls pt_envelopes