pt_three_phase_from_intersection – fenvelopes
pt_three_phase_from_intersection Subroutine
MIT
36 statements
Source File
public subroutine pt_three_phase_from_intersection(pt_x, pt_y, intersections, pt_x_3, pt_y_3)
Uses
linalg
legacy_ar_models
Arguments
Type Intent Optional Attributes Name
type(envelope), intent(in) :: pt_x
type(envelope), intent(in) :: pt_y
type(point), intent(in) :: intersections(:)
type(PTEnvel3), intent(out) :: pt_x_3(:)
type(PTEnvel3), intent(out) :: pt_y_3(:)
Calls
Called by
Contents
Variables
X beta del_S0 i i_inter j lnKx lnKy ns p phase_x phase_y t
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, allocatable :: X(:)
real(kind=pr), public :: beta
real(kind=pr), public :: del_S0
integer, public :: i
integer, public :: i_inter = 1
integer, public :: j
real(kind=pr), public, allocatable :: lnKx(:)
real(kind=pr), public, allocatable :: lnKy(:)
integer, public :: ns
real(kind=pr), public :: p
real(kind=pr), public, allocatable :: phase_x(:)
real(kind=pr), public, allocatable :: phase_y(:)
real(kind=pr), public :: t
Call graph
pt_three_phase_from_intersection calls interpol, pt_envelope_three_phase
pt_envelope_three_phase calls xnew, k, break_conditions_three_phases, dxds_in, str, full_newton, solve_system, progress_bar, knew
full_newton calls solve_system, optval
solve_system calls dgesv
pt_envelopes calls pt_three_phase_from_intersection
main calls pt_envelopes