px_envelopes – fenvelopes
px_envelopes Subroutine
MIT
56 statements
Source File
subroutine px_envelopes()
Uses
linalg
dsp_lines
inj_envelopes
envelopes
Calculation of P envelopes at selected temperature.
Arguments
None
Calls
Called by
Contents
Variables
inter_dew_bub self_inter_bub self_inter_dew t_tol
Variables
Type Visibility Attributes Name Initial
type(point), public, allocatable :: inter_dew_bub(:)
type(point), public, allocatable :: self_inter_bub(:)
type(point), public, allocatable :: self_inter_dew(:)
real(kind=pr), public :: t_tol = 2
Call graph
px_envelopes calls px_two_phase_from_pt, dsp_line_from_dsp_px, px_three_phase_from_inter, px_branch_3, intersection, px_three_phase_from_pt, px_hpl_line, dsps
px_two_phase_from_pt calls optval, interpol, injection_envelope
dsp_line_from_dsp_px calls optval, interpol, get_z, dsp_line
px_three_phase_from_inter calls optval, interpol, get_z, injection_envelope_three_phase
intersection calls intersect_two_lines, intersect_one_line
px_three_phase_from_pt calls optval, interpol, injection_envelope_three_phase
px_hpl_line calls foo, injection_envelope, optim
intersect_two_lines calls intersects
injection_envelope calls get_z, update_spec, xnew, fix_step_two_phases, full_newton, progress_bar, str, knew, break_conditions
dsp_line calls update_spec, full_newton, progress_bar, str, fix_step, break_conditions_dsp_line
injection_envelope_three_phase calls get_z, update_spec, dxds_in, full_newton, progress_bar, str, knew, break_conditions_three_phases
intersect_one_line calls intersects
update_spec calls solve_system
nm_opt calls nelmin
intersects calls solve_system
full_newton calls optval, solve_system
solve_system calls dgesv
main calls px_envelopes