px_hpl_line – fenvelopes
px_hpl_line Function
MIT
66 statements
Source File
public function px_hpl_line(alpha_0, p)
Uses
linalg
legacy_ar_models
legacy_thermo_properties
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: alpha_0
Staring to search
real(kind=pr), intent(in) :: p
Pressure of HPLL
Return Value type(injelope)
Resulting HPLL line
Calls
Called by
Contents
Variables
alpha_in del_S0 diff dlnphi_dp_y dlnphi_dp_z dlnphi_dy dlnphi_dz k lnfug_y lnfug_z ncomp ns p_in v x y z
Functions
foo
Subroutines
optim
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: alpha_in
real(kind=pr), public :: del_S0
real(kind=pr), public :: diff
real(kind=pr), public :: dlnphi_dp_y(nc)
real(kind=pr), public :: dlnphi_dp_z(nc)
real(kind=pr), public :: dlnphi_dy(nc,nc)
real(kind=pr), public :: dlnphi_dz(nc,nc)
real(kind=pr), public :: k(nc)
real(kind=pr), public :: lnfug_y(nc)
real(kind=pr), public :: lnfug_z(nc)
integer, public :: ncomp
integer, public :: ns
real(kind=pr), public :: p_in
real(kind=pr), public :: v
real(kind=pr), public, allocatable :: x(:)
real(kind=pr), public :: y(nc)
real(kind=pr), public :: z(nc)
Functions
function foo(x) result(f)
Arguments
Type Intent Optional Attributes Name
real(kind=pr) :: x(:)
Return Value real(kind=pr)
Subroutines
subroutine optim()
Arguments
None
Call graph
px_hpl_line calls foo, optim, injection_envelope
injection_envelope calls update_spec, fix_step_two_phases, str, knew, break_conditions, get_z, full_newton, xnew
update_spec calls solve_system
nm_opt calls nelmin
full_newton calls solve_system, optval
solve_system calls dgesv
px_envelopes calls px_hpl_line
main calls px_envelopes