px_three_phase_from_inter – fenvelopes
px_three_phase_from_inter Function
MIT
38 statements
Source File
public function px_three_phase_from_inter(inter, px_1, px_2, del_S0, beta0) result(envels)
Uses
linalg
legacy_ar_models
stdlib_optval
Arguments
Type Intent Optional Attributes Name
type(point), intent(in) :: inter
type(injelope), intent(in) :: px_1
type(injelope), intent(in) :: px_2
real(kind=pr), optional :: del_S0
real(kind=pr), optional :: beta0
Return Value type(injelope)(2)
Calls
Called by
Contents
Variables
X alpha beta del_S dzda i j lnKx lnKy ns p phase_x phase_y z
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: X(2*nc+3)
real(kind=pr), public :: alpha
real(kind=pr), public :: beta
real(kind=pr), public :: del_S
real(kind=pr), public :: dzda(nc)
integer, public :: i
integer, public :: j
real(kind=pr), public :: lnKx(nc)
real(kind=pr), public :: lnKy(nc)
integer, public :: ns
real(kind=pr), public :: p
real(kind=pr), public :: phase_x(nc)
real(kind=pr), public :: phase_y(nc)
real(kind=pr), public :: z(nc)
Call graph
px_three_phase_from_inter calls optval, injection_envelope_three_phase, interpol, get_z
injection_envelope_three_phase calls get_z, update_spec, break_conditions_three_phases, knew, progress_bar, full_newton, str, dxds_in
update_spec calls solve_system
full_newton calls solve_system
solve_system calls dgesv
px_envelopes calls px_three_phase_from_inter
main calls px_envelopes