px_two_phase_from_pt – fenvelopes
px_two_phase_from_pt Function
MIT
34 statements
Source File
public function px_two_phase_from_pt(t_inj, pt_env_2, t_tol, del_S0) result(px_envels)
Uses
linalg
stdlib_optval
Calculate two phase Px envelopes at a given injection temperature.
Given an injection temperature t_inj and a base PT envelope pt_env_2, finds all the points on the PT envelope near t_inj, based on an absolute tolerance t_tol. These points are used as initialization for calculation of Px envelopes.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: t_inj
Injection temperature [K]
type(envelope), intent(in) :: pt_env_2
Base PT envelope
real(kind=pr), intent(in) :: t_tol
Absolute temperature tolerance
real(kind=pr), intent(in), optional :: del_S0
First point
Return Value type(injelope),allocatable,(:)
Output Px envelope
Calls
Called by
Contents
Variables
X alpha del_S i idx k ns p pold px_envel ts_envel
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, allocatable :: X(:)
Vector of variables
real(kind=pr), public :: alpha
Amount of injection
real(kind=pr), public :: del_S
integer, public :: i
integer, public :: idx
real(kind=pr), public, allocatable :: k(:)
K values
integer, public :: ns
real(kind=pr), public :: p
Pressure of ocurrence
real(kind=pr), public :: pold
Old pressure, used to assure no repeats
type(injelope), public :: px_envel
real(kind=pr), public, allocatable :: ts_envel(:)
Temperatures under tolerance
Call graph
px_two_phase_from_pt calls optval, interpol, injection_envelope
injection_envelope calls get_z, update_spec, xnew, fix_step_two_phases, full_newton, progress_bar, str, knew, break_conditions
update_spec calls solve_system
full_newton calls optval, solve_system
solve_system calls dgesv
px_envelopes calls px_two_phase_from_pt
main calls px_envelopes