px_three_phase_from_pt – fenvelopes
px_three_phase_from_pt Function
MIT
41 statements
Source File
public function px_three_phase_from_pt(t_inj, pt_env_3, t_tol, del_S0) result(envel)
Uses
linalg
envelopes
stdlib_optval
Calculate three phase Px envelopes at a given injection temperature.
Given an injection temperature t_inj and a base PT envelope pt_env_3, finds all the points on the PT envelope near t_inj, based on an absolute tolerance t_tol. These points are used as initialization for calculation of Px envelopes.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: t_inj
Injection temperature [K]
type(PTEnvel3), intent(in) :: pt_env_3(:)
Base PT envelopes
real(kind=pr), intent(in) :: t_tol
Absolute temperature tolerance
real(kind=pr), intent(in), optional :: del_S0
First point
Return Value type(injelope)
Output Px envelope
Calls
Called by
Contents
Variables
X alpha beta del_S i i_envel idx kx ky ns p pold ts_envel
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, allocatable :: X(:)
Vector of variables
real(kind=pr), public :: alpha
Amount of injection
real(kind=pr), public :: beta
Main phases molar fraction
real(kind=pr), public :: del_S
integer, public :: i
integer, public :: i_envel
integer, public :: idx
real(kind=pr), public, allocatable :: kx(:)
K values
real(kind=pr), public, allocatable :: ky(:)
K values
integer, public :: ns
real(kind=pr), public :: p
Pressure of ocurrence
real(kind=pr), public :: pold
Old pressure, used to assure no repeats
real(kind=pr), public, allocatable :: ts_envel(:)
Temperatures under tolerance
Call graph
px_three_phase_from_pt calls optval, injection_envelope_three_phase, interpol
injection_envelope_three_phase calls get_z, update_spec, dxds_in, full_newton, progress_bar, str, knew, break_conditions_three_phases
update_spec calls solve_system
full_newton calls optval, solve_system
solve_system calls dgesv
px_envelopes calls px_three_phase_from_pt
main calls px_envelopes