read_srk – fenvelopes
read_srk Subroutine
MIT
16 statements
Source File
private subroutine read_srk()
Read SRK model parameters
options:
spec=critical -> Use critical constants
spec=parameters -> Use EoS parameters
Critical constants EoS parameters
Arguments
None
Calls
Called by
Contents
None
Call graph
read_srk calls srk_factory
read_components calls read_srk
read_system calls read_components
setup calls read_system
main calls setup