read_components – fenvelopes
read_components Subroutine
MIT
26 statements
Source File
private subroutine read_components()
Read components Read kij and lij matrixes Since in the ClassicVdW mixing rules the bij matrix is constant it’s stored beforehand
Arguments
None
Calls
Called by
Contents
Variables
i j
Variables
Type Visibility Attributes Name Initial
integer, private :: i
integer, private :: j
Call graph
read_components calls read_srk, read_kij_lij, lij, b, bij, read_pr76, read_pr78
read_srk calls srk_factory
read_kij_lij calls lij, kij
read_pr76 calls pr76_factory
read_pr78 calls pr78_factory
read_system calls read_components
setup calls read_system
main calls setup