read_system – fenvelopes
read_system Subroutine
MIT
7 statements
Source File
public subroutine read_system(filepath)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: filepath
Calls
Called by
Contents
None
Call graph
read_system calls setup_input, read_model, read_components
read_model calls z, setup
read_components calls read_srk, bij, read_pr78, read_kij_lij, read_pr76, b, lij
read_srk calls srk_factory
read_pr78 calls pr78_factory
read_kij_lij calls lij, kij
read_pr76 calls pr76_factory
setup calls read_system
main calls setup