setup – fenvelopes
setup Subroutine
MIT
15 statements
Source File
subroutine setup()
Uses
inj_envelopes
io_nml
Setup system
Make output folder (if necessary) and/or clean everyhing in an existing one. Then read input files to setup needed parameters.
Arguments
None
Calls
Called by
Contents
Variables
funit_system infile
Variables
Type Visibility Attributes Name Initial
integer, public :: funit_system
character(len=500), public :: infile
Call graph
setup calls setup_cli, read_system, from_nml, write_system
read_system calls setup_input, read_components, read_model
write_system calls lij, str, kij
read_components calls lij, read_srk, read_pr76, read_pr78, read_kij_lij, bij, b
read_model calls setup, z
read_srk calls srk_factory
read_pr76 calls pr76_factory
read_pr78 calls pr78_factory
read_kij_lij calls lij, kij
main calls setup