solve_system – fenvelopes
solve_system Function
MIT
27 statements
Source File
public function solve_system(a, b) result(x)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: a(size(b),size(b))
real(kind=pr), intent(in) :: b(:)
Return Value real(kind=pr)(size(b))
Calls
Called by
Contents
Variables
a_lapack b_lapack info ipiv lda ldb n nrhs
Interfaces
dgesv
Variables
Type Visibility Attributes Name Initial
real(kind=8), public :: a_lapack(size(b),size(b))
real(kind=8), public :: b_lapack(size(b))
integer, public :: info
integer, public :: ipiv(size(b))
integer, public :: lda
integer, public :: ldb
integer, public :: n
integer, public :: nrhs
Interfaces
interface
subroutine dgesv(n, nrhs, a, lda, ipiv, b, ldb, info)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: nrhs
real(kind=8) :: a(n,n)
integer :: lda
integer :: ipiv(n)
real(kind=8) :: b(n)
integer :: ldb
integer :: info
Call graph
solve_system calls dgesv
envelope2 calls solve_system, update_specification
update_spec calls solve_system
pt_envelope_three_phase calls solve_system, full_newton
update_specification calls solve_system
intersects calls solve_system
full_newton calls solve_system
pt_envelopes calls envelope2, pt_envelope_three_phase, pt_three_phase_from_intersection, get_case
pt_three_phase_from_intersection calls pt_envelope_three_phase
intersect_two_lines calls intersects
injection_envelope_three_phase calls update_spec, full_newton
injection_envelope calls update_spec, full_newton
dsp_line calls update_spec, full_newton
intersect_one_line calls intersects
px_three_phase_from_pt calls injection_envelope_three_phase
px_three_phase_from_inter calls injection_envelope_three_phase
intersection calls intersect_two_lines, intersect_one_line
px_two_phase_from_pt calls injection_envelope
dsp_line_from_dsp calls dsp_line
dsp_line_from_dsp_px calls dsp_line
main calls pt_envelopes, px_envelopes
px_hpl_line calls injection_envelope
px_envelopes calls px_three_phase_from_pt, px_three_phase_from_inter, intersection, px_two_phase_from_pt, dsp_line_from_dsp_px, px_hpl_line
get_case calls intersection