update_spec – fenvelopes
update_spec Subroutine
MIT
19 statements
Source File
public subroutine update_spec(X, ns, del_S, dF, dXdS)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
integer, intent(inout) :: ns
real(kind=pr), intent(inout) :: del_S
real(kind=pr), intent(in) :: dF(size(X),size(X))
real(kind=pr), intent(inout) :: dXdS(size(X))
Calls
Called by
Contents
Variables
dFdS n ns_new
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: dFdS(size(X))
integer, public :: n
integer, public :: ns_new
Call graph
update_spec calls solve_system
solve_system calls dgesv
injection_envelope calls update_spec
injection_envelope_three_phase calls update_spec
dsp_line calls update_spec
px_three_phase_from_pt calls injection_envelope_three_phase
dsp_line_from_dsp calls dsp_line
px_two_phase_from_pt calls injection_envelope
px_three_phase_from_inter calls injection_envelope_three_phase
dsp_line_from_dsp_px calls dsp_line
px_hpl_line calls injection_envelope
px_envelopes calls px_three_phase_from_pt, px_two_phase_from_pt, px_three_phase_from_inter, dsp_line_from_dsp_px, px_hpl_line
main calls px_envelopes