intersection – fenvelopes
intersection Interface
MIT
4 statements
Source File
public interface intersection
Calls
Called by
Contents
Module Procedures
intersect_two_lines intersect_one_line
Module Procedures
public function intersect_two_lines(l1_x, l1_y, l2_x, l2_y) result(intersections)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: l1_x(:)
real(kind=pr), intent(in) :: l1_y(:)
real(kind=pr), intent(in) :: l2_x(:)
real(kind=pr), intent(in) :: l2_y(:)
Return Value type(point),allocatable, (:)
public function intersect_one_line(lx, ly) result(intersections)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: lx(:)
real(kind=pr), intent(in) :: ly(:)
Return Value type(point),allocatable, (:)
Call graph
intersection calls intersect_two_lines, intersect_one_line
intersect_two_lines calls intersects
intersect_one_line calls intersects
intersects calls solve_system
solve_system calls dgesv
get_case calls intersection
px_envelopes calls intersection
pt_envelopes calls get_case
main calls px_envelopes, pt_envelopes