main – fenvelopes
main Program
MIT
192 statements
Source File
Uses
inj_envelopes
flap
constants
envelopes
stdlib_ansi
legacy_ar_models
dtypes
Calls
Contents
Variables
alpha cli cli_error cli_string et pt_bub pt_bub_3 pt_bub_t0 pt_dew pt_dew_3 pt_dew_t0 pt_hpl px_bub px_dew px_hpl st
Subroutines
pt_envelopes px_envelopes setup setup_cli
Variables
Type Attributes Name Initial
real(kind=pr) :: alpha = 0.0
type(command_line_interface) :: cli
integer :: cli_error
character(len=99) :: cli_string
real(kind=pr) :: et
type(envelope) :: pt_bub
Shared 2ph-PT envelopes
type(PTEnvel3), allocatable :: pt_bub_3(:)
Shared 3ph-PT envelopes
real(kind=pr) :: pt_bub_t0 = 180
type(envelope) :: pt_dew
Shared 2ph-PT envelopes
type(PTEnvel3), allocatable :: pt_dew_3(:)
Shared 3ph-PT envelopes
real(kind=pr) :: pt_dew_t0 = 180
type(envelope) :: pt_hpl
Shared 2ph-PT envelopes
type(injelope), allocatable :: px_bub(:)
Shared 2ph-Px envelopes
type(injelope), allocatable :: px_dew(:)
Shared 2ph-Px envelopes
type(injelope), allocatable :: px_hpl
Shared 2ph-Px envelopes
real(kind=pr) :: st
Subroutines
subroutine pt_envelopes()
Calculation of PT envelopes of the main system.
Arguments
None
subroutine px_envelopes()
Calculation of P envelopes at selected temperature.
Arguments
None
subroutine setup()
Setup system
Read more…
Arguments
None
subroutine setup_cli()
Setup CLI subroutine
Read more…
Arguments
None
Call graph
main calls setup, get_z, px_envelopes, pt_envelopes
setup calls setup_cli, read_system, from_nml, write_system
px_envelopes calls dsp_line_from_dsp_px, intersection, px_branch_3, dsps, px_two_phase_from_pt, px_three_phase_from_inter, px_three_phase_from_pt, px_hpl_line
pt_envelopes calls pt_envelope_three_phase, lnkx, k_wilson, phase_y, k_wilson_bubble, find_hpl, lnphiy, x, z, p_wilson, get_case, phase_x, lnky, envelope2, termo, lnphix, pt_three_phase_from_intersection
dsp_line_from_dsp_px calls get_z, interpol, dsp_line, optval
pt_envelope_three_phase calls k, break_conditions_three_phases, xnew, dxds_in, full_newton, knew, str, solve_system, progress_bar
intersection calls intersect_two_lines, intersect_one_line
k_wilson_bubble calls k_wilson
find_hpl calls z, termo
read_system calls read_model, setup_input, read_components
get_case calls intersection
px_two_phase_from_pt calls injection_envelope, interpol, optval
write_system calls lij, kij, str
px_three_phase_from_inter calls get_z, injection_envelope_three_phase, interpol, optval
px_three_phase_from_pt calls injection_envelope_three_phase, interpol, optval
envelope2 calls fix_delx, f2, xin, update_specification, m, str, solve_system, delta_x
pt_three_phase_from_intersection calls pt_envelope_three_phase, interpol
px_hpl_line calls injection_envelope, foo, optim
intersect_two_lines calls intersects
f2 calls termo
read_model calls z, setup
injection_envelope calls get_z, xnew, full_newton, knew, str, progress_bar, update_spec, fix_step_two_phases, break_conditions
injection_envelope_three_phase calls get_z, dxds_in, full_newton, knew, str, progress_bar, update_spec, break_conditions_three_phases
update_specification calls solve_system, dfds
full_newton calls optval, solve_system
dsp_line calls full_newton, str, progress_bar, update_spec, fix_step, break_conditions_dsp_line
intersect_one_line calls intersects
solve_system calls dgesv
read_components calls lij, read_srk, bij, read_pr78, read_kij_lij, read_pr76, b
update_spec calls solve_system
nm_opt calls nelmin
read_srk calls srk_factory
intersects calls solve_system
read_pr78 calls pr78_factory
read_kij_lij calls lij, kij
read_pr76 calls pr76_factory